---

- name: "Launch instance"
  local_action:
    module: ec2
    instance_type: "t2.nano"
    image: "ami-bff32ccc"
    wait: yes
    group: "{{ instance_group }}"
    vpc_subnet_id: "subnet-aa00f5dd"
    region: "eu-west-1"
    instance_tags:
      Name: "{{ instance_name }}"
      Type: "{{ instance_type }}"
    key_name: "{{ instance_key_name }}"
    instance_profile_name: "{{ instance_role }}"
  register: ec2

- name: Wait for SSH to come up
  local_action:
    module: wait_for
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  with_items: ec2.instances
